version: '3.8'
services:
  bachend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=db
    
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=db
      
    restart: always

    