# Generated by Django 4.1 on 2022-11-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_qrcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="qr_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
