# Generated by Django 4.1 on 2022-11-02 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_alter_qrcode_options_qrcode_verfication_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="verfication_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
