# Generated by Django 4.1 on 2022-08-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "onlinecourse",
            "0002_choice_enrollment_progress_submission_question_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="chocies",
            new_name="choices",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_grade",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="is_correct",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="is_graded",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="is_submitted",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="submission_date",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="submission_grade",
        ),
        migrations.AddField(
            model_name="question",
            name="grade",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(max_length=300),
        ),
    ]
