# Generated by Django 4.1 on 2022-08-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlinecourse", "0004_learner_can_join_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learner",
            name="social_link",
            field=models.URLField(blank=True),
        ),
    ]
