# Generated by Django 4.1 on 2022-08-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlinecourse", "0005_alter_learner_social_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="embded_video",
            field=models.TextField(null=True),
        ),
    ]
