# Generated by Django 4.1 on 2022-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlinecourse", "0006_lesson_embded_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_title",
            field=models.CharField(default="title", max_length=200),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="embded_video",
            field=models.BooleanField(default=False),
        ),
    ]
