# Generated by Django 4.1 on 2022-08-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlinecourse", "0007_lesson_video_link_lesson_video_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to="profile_pictures/"),
        ),
    ]
