# Generated by Django 4.0.4 on 2022-09-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0010_remove_course_instructors_course_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='mode',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('instructor', 'instructor'), ('manager', 'manager')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_title',
            field=models.CharField(blank=True, default='title', max_length=200),
        ),
    ]
