name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.6
    - name: Install Dependencies
      run: |
        make install
    - name: Format code
      run: |
        make format
    - name: Lint with pylint
      run: |
        make lint
    - name: Build Container
      run: |
        make build
    - name: Run Container
      run: |
        make up
    - name: Run website
      run: |
        make makemigrations && make run
    - name: Run Tests
      run: |
        python manage.py test
      
